services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=db
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DB=e-commerce
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


volumes:
  mongo-data:
